#!/bin/bash

INFO_CMUS=$(cmus-remote -Q 2>/dev/null)
if [[ $? -eq 0 ]]; then
  INFO_TITLE=$(echo "${INFO_CMUS}" | sed -n -e 's/^.*title//p' | head -n 1)
  INFO_ALBUM=$(echo "${INFO_CMUS}" | sed -n -e 's/^.*album//p' | head -n 1)
  INFO_ARTIST=$(echo "${INFO_CMUS}" | sed -n -e 's/^.*artist//p' | head -n 1)
  DURATION=$(echo "${INFO_CMUS}" | sed -n -e 's/^.*duration//p' | head -n 1)
  POSITION=$(echo "${INFO_CMUS}" | sed -n -e 's/^.*position//p' | head -n 1)
  DURATION_MIN=$((DURATION / 60))
  DURATION_SEC=$((DURATION % 60))
  DURATION_FORMAT=$(printf %02d:%02d $DURATION_MIN $DURATION_SEC)
  POSITION_MIN=$((POSITION / 60))
  POSITION_SEC=$((POSITION % 60))
  POSITION_FORMAT=$(printf %02d:%02d $POSITION_MIN $POSITION_SEC)
else
  exit
fi

if [[ "${INFO_ARTIST}" ]] && [[ "${INFO_TITLE}" ]]; then
	OUT_TEXT="${INFO_ARTIST} -${INFO_TITLE} ($POSITION_FORMAT / $DURATION_FORMAT)"
elif [[ "${INFO_TITLE}" ]]; then
	OUT_TEXT="${INFO_TITLE} ($POSITION_FORMAT / $DURATION_FORMAT)"
fi

echo "${OUT_TEXT}"
exit
