#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal

# Source generated colors.
source "${HOME}/.cache/wal/colors.sh"

reload_dunst() {
    pkill dunst && \
        dunst \
            -lb "$color0" \
            -nb "$color0" \
            -cb "$color0" \
            -lf "$color15" \
            -bf "$color15" \
            -cf "$color15" \
            -nf "$color15" \
            -fn "${DUNST_FONT:-Misc Termsyn 10}" \
            -geometry "${DUNST_SIZES:-300x30-40+70}" &
}

reload_bar(){
    sh /home/yuimaestro/.config/polybar/launch.sh
}

main() {
    reload_dunst &
    reload_bar
    # pgrep i3 && i3-msg reload &
}

main >/dev/null 2>&1
