(deftheme blackvoid
  "Created 2019-10-14.")

(custom-theme-set-faces
 'blackvoid
 '(default ((t (:family "Hack" :foundry "SRC" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#BABABA" :background "#000000" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#BABABA"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#41728e"))))
 '(highlight ((t (:foreground "#0d0d0d" :background "#41728e"))))
 '(region ((t (:background "#333537"))))
 '(shadow ((t (:foreground "#5c5e5e"))))
 '(secondary-selection ((t (:background "#5a5b5a"))))
 '(trailing-whitespace ((t (:background "#BF5460"))))
 '(font-lock-builtin-face ((t (:foreground "#698EA2"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#5a5b5a"))))
 '(font-lock-constant-face ((t (:foreground "#B18FB5"))))
 '(font-lock-doc-face ((t (:foreground "#717171" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:foreground "#698EA2"))))
 '(font-lock-keyword-face ((t (:foreground "#B18FB5"))))
 '(font-lock-negation-char-face ((t (:foreground "#BABABA" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#BABABA" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#BABABA" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#BABABA" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#E9AFD8"))))
 '(font-lock-type-face ((t (:foreground "#8DB78A"))))
 '(font-lock-variable-name-face ((t (:foreground "#BF5460"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#82B8A9"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#3f4040" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#BABABA" :background "#292b2b"))))
 '(mode-line ((t (:box nil :foreground "#ffffff" :background "#18191b"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#698EA2"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#5a5b5a" :background "#000000"))))
 '(isearch ((t (:weight bold :foreground "#0d0d0d" :background "#698EA2"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:weight bold :foreground "#ffffff" :background "#698EA2"))))
 '(match ((t (:weight bold :foreground "#B18FB5" :background "#0d0d0d"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'blackvoid)
